// <auto-generated />
using LaBouchee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaBouchee.Migrations
{
    [DbContext(typeof(LaBoucheeDbContext))]
    [Migration("20231114105555_SeedProductsTable")]
    partial class SeedProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaBouchee.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isTrendingProduct")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Delicate layers of buttery, flaky pastry embrace a rich chocolate center, creating a blissful harmony of textures and flavors.",
                            ImageUrl = "https://i.postimg.cc/J0sq4xP1/Painauchocolat.jpg",
                            Name = "Pain au Chocolat",
                            Price = 3m,
                            isTrendingProduct = true
                        },
                        new
                        {
                            Id = 2,
                            Detail = " Handcrafted to golden buttery perfection, each layer unfolds with a crisp exterior and a soft, airy interior.",
                            ImageUrl = "https://i.postimg.cc/sg7Thnyx/Croissant.jpg",
                            Name = "Croissant",
                            Price = 2m,
                            isTrendingProduct = true
                        },
                        new
                        {
                            Id = 3,
                            Detail = "A symphony of flaky crust and velvety filling, our handcrafted quiches are a delightful blend of premium ingredients.",
                            ImageUrl = "https://i.postimg.cc/wvf2pZ5f/Quiche.jpg",
                            Name = "Quiche",
                            Price = 5m,
                            isTrendingProduct = true
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Delicate choux pastry embraces a velvety center, each bite a symphony of textures and flavors.",
                            ImageUrl = "https://i.postimg.cc/tg4cKL8f/Eclair.jpg",
                            Name = "Eclair",
                            Price = 3m,
                            isTrendingProduct = true
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Layers of flaky puff pastry and luscious pastry cream.",
                            ImageUrl = "https://i.postimg.cc/TYxt8zD9/Millefeuille.jpg",
                            Name = "Mille-Feuille",
                            Price = 3m,
                            isTrendingProduct = true
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Savor the charm of our Madeleines — petite, shell-shaped cakes with a soft, buttery texture.",
                            ImageUrl = "https://i.postimg.cc/vHv3G07d/Madeleines.jpg",
                            Name = "Madeleines",
                            Price = 1m,
                            isTrendingProduct = true
                        },
                        new
                        {
                            Id = 7,
                            Detail = "These delicate almond meringue cookies, with a crisp exterior and a luscious filling, promise a burst of flavor in every bite.",
                            ImageUrl = "https://i.postimg.cc/c1wFbxrC/Macarons.jpg",
                            Name = "Macaron",
                            Price = 3m,
                            isTrendingProduct = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
